import { DAEGU_DIRECT_INSTITUTIONS } from "@/lib/daegu-direct-institutions";
import { DEFAULT_OFFICE_CODE, NATIONWIDE_OFFICE_CODE } from "@/lib/regions";
import type { Institution } from "@/lib/types";

export const DUMMY_INSTITUTIONS: Institution[] = [
  ...DAEGU_DIRECT_INSTITUTIONS,
  {
    id: "dummy-knu",
    name: "경북대학교",
    type: "school",
    address: "대구광역시 북구 대학로 80",
    district: "북구",
    officeCode: "D10",
    lat: 35.89066,
    lng: 128.61199,
    source: "dummy",
  },
  {
    id: "dummy-daeryun",
    name: "대륜고등학교",
    type: "school",
    address: "대구광역시 수성구 달구벌대로496길 50",
    district: "수성구",
    officeCode: "D10",
    lat: 35.85841,
    lng: 128.63812,
    source: "dummy",
  },
  {
    id: "dummy-daegu-hs",
    name: "대구고등학교",
    type: "school",
    address: "대구광역시 수성구 희망로36길 47",
    district: "수성구",
    officeCode: "D10",
    lat: 35.83855,
    lng: 128.61842,
    source: "dummy",
  },
  {
    id: "dummy-kyungshin",
    name: "경신고등학교",
    type: "school",
    address: "대구광역시 수성구 청수로69길 21",
    district: "수성구",
    officeCode: "D10",
    lat: 35.84112,
    lng: 128.63488,
    source: "dummy",
  },
  {
    id: "dummy-ohsung",
    name: "오성고등학교",
    type: "school",
    address: "대구광역시 달서구 학산로 130",
    district: "달서구",
    officeCode: "D10",
    lat: 35.85102,
    lng: 128.55741,
    source: "dummy",
  },
  {
    id: "dummy-chunggu",
    name: "청구고등학교",
    type: "school",
    address: "대구광역시 동구 효동로2길 24",
    district: "동구",
    officeCode: "D10",
    lat: 35.88235,
    lng: 128.65021,
    source: "dummy",
  },
  {
    id: "dummy-neungin",
    name: "능인고등학교",
    type: "school",
    address: "대구광역시 수성구 명덕로 417",
    district: "수성구",
    officeCode: "D10",
    lat: 35.84528,
    lng: 128.61573,
    source: "dummy",
  },
  {
    id: "dummy-dfhs",
    name: "대구외국어고등학교",
    type: "school",
    address: "대구광역시 수성구 청호로 76",
    district: "수성구",
    officeCode: "D10",
    lat: 35.84691,
    lng: 128.63955,
    source: "dummy",
  },
  {
    id: "dummy-dshs",
    name: "대구일과학고등학교",
    type: "school",
    address: "대구광역시 수성구 동대구로54길 29",
    district: "수성구",
    officeCode: "D10",
    lat: 35.85888,
    lng: 128.63142,
    source: "dummy",
  },
  {
    id: "dummy-kmu",
    name: "계명대학교",
    type: "school",
    address: "대구광역시 달서구 달구벌대로 1095",
    district: "달서구",
    officeCode: "D10",
    lat: 35.85721,
    lng: 128.48735,
    source: "dummy",
  },
  {
    id: "dummy-yeungjin",
    name: "영진전문대학교",
    type: "school",
    address: "대구광역시 북구 복현로 35",
    district: "북구",
    officeCode: "D10",
    lat: 35.89642,
    lng: 128.61518,
    source: "dummy",
  },
  {
    id: "dummy-daegu-girls",
    name: "대구여자고등학교",
    type: "school",
    address: "대구광역시 중구 명덕로 130",
    district: "중구",
    officeCode: "D10",
    lat: 35.86012,
    lng: 128.59044,
    source: "dummy",
  },
  {
    id: "dummy-gyeongsan-ms",
    name: "경상중학교",
    type: "school",
    address: "대구광역시 중구 달구벌대로 2120",
    district: "중구",
    officeCode: "D10",
    lat: 35.86635,
    lng: 128.59891,
    source: "dummy",
  },
  {
    id: "dummy-seodaegu-es",
    name: "서대구초등학교",
    type: "school",
    address: "대구광역시 서구 국채보상로34길 32",
    district: "서구",
    officeCode: "D10",
    lat: 35.87188,
    lng: 128.55962,
    source: "dummy",
  },
  {
    id: "dummy-namsan-es",
    name: "남산초등학교",
    type: "school",
    address: "대구광역시 중구 남산로 61",
    district: "중구",
    officeCode: "D10",
    lat: 35.85944,
    lng: 128.58721,
    source: "dummy",
  },
  {
    id: "dummy-ansim-ms",
    name: "안심중학교",
    type: "school",
    address: "대구광역시 동구 안심로49길 18",
    district: "동구",
    officeCode: "D10",
    lat: 35.87112,
    lng: 128.71844,
    source: "dummy",
  },
  {
    id: "dummy-chilgok-ms",
    name: "칠곡중학교",
    type: "school",
    address: "대구광역시 북구 동암로 12",
    district: "북구",
    officeCode: "D10",
    lat: 35.94218,
    lng: 128.55833,
    source: "dummy",
  },
  {
    id: "dummy-sungseo-hs",
    name: "성서고등학교",
    type: "school",
    address: "대구광역시 달서구 학산로 157",
    district: "달서구",
    officeCode: "D10",
    lat: 35.84966,
    lng: 128.55102,
    source: "dummy",
  },
  {
    id: "dummy-hwawon-hs",
    name: "화원고등학교",
    type: "school",
    address: "대구광역시 달성군 화원읍 비슬로 2584",
    district: "달성군",
    officeCode: "D10",
    lat: 35.80421,
    lng: 128.50018,
    source: "dummy",
  },
  {
    id: "dummy-gunwi-hs",
    name: "군위고등학교",
    type: "school",
    address: "대구광역시 군위군 군위읍 군청로 138",
    district: "군위군",
    officeCode: "D10",
    lat: 36.24288,
    lng: 128.57264,
    source: "dummy",
  },
  {
    id: "dummy-yeongnam",
    name: "영남이공대학교",
    type: "school",
    address: "대구광역시 남구 현충로 170",
    district: "남구",
    officeCode: "D10",
    lat: 35.84566,
    lng: 128.59312,
    source: "dummy",
  },
  {
    id: "dummy-daegu-tech-hs",
    name: "대구공업고등학교",
    type: "school",
    address: "대구광역시 남구 현충로 21",
    district: "남구",
    officeCode: "D10",
    lat: 35.84688,
    lng: 128.58041,
    source: "dummy",
  },
  {
    id: "dummy-seoul-office",
    name: "서울특별시교육청",
    type: "office",
    address: "서울특별시 종로구 송월길 48",
    district: "종로구",
    officeCode: "B10",
    lat: 37.5729,
    lng: 126.9618,
    source: "dummy",
  },
  {
    id: "dummy-seoul-hs",
    name: "서울고등학교",
    type: "school",
    address: "서울특별시 서초구 효령로 197",
    district: "서초구",
    officeCode: "B10",
    lat: 37.4838,
    lng: 127.0056,
    source: "dummy",
  },
  {
    id: "dummy-busan-office",
    name: "부산광역시교육청",
    type: "office",
    address: "부산광역시 연제구 중앙대로 2222",
    district: "연제구",
    officeCode: "C10",
    lat: 35.176,
    lng: 129.075,
    source: "dummy",
  },
  {
    id: "dummy-incheon-office",
    name: "인천광역시교육청",
    type: "office",
    address: "인천광역시 남동구 정각로 9",
    district: "남동구",
    officeCode: "E10",
    lat: 37.4485,
    lng: 126.7313,
    source: "dummy",
  },
  {
    id: "dummy-gwangju-office",
    name: "광주광역시교육청",
    type: "office",
    address: "광주광역시 서구 화운로 117",
    district: "서구",
    officeCode: "F10",
    lat: 35.1522,
    lng: 126.8513,
    source: "dummy",
  },
  {
    id: "dummy-daejeon-office",
    name: "대전광역시교육청",
    type: "office",
    address: "대전광역시 서구 청사로 130",
    district: "서구",
    officeCode: "G10",
    lat: 36.3575,
    lng: 127.3812,
    source: "dummy",
  },
  {
    id: "dummy-ulsan-office",
    name: "울산광역시교육청",
    type: "office",
    address: "울산광역시 남구 꽃대나리로 196",
    district: "남구",
    officeCode: "H10",
    lat: 35.5388,
    lng: 129.3301,
    source: "dummy",
  },
  {
    id: "dummy-sejong-office",
    name: "세종특별자치시교육청",
    type: "office",
    address: "세종특별자치시 한누리대로 2154",
    district: "세종시",
    officeCode: "I10",
    lat: 36.4796,
    lng: 127.2892,
    source: "dummy",
  },
  {
    id: "dummy-gyeonggi-office",
    name: "경기도교육청",
    type: "office",
    address: "경기도 수원시 영통구 도청로 30",
    district: "수원시",
    officeCode: "J10",
    lat: 37.2749,
    lng: 127.0095,
    source: "dummy",
  },
  {
    id: "dummy-gangwon-office",
    name: "강원특별자치도교육청",
    type: "office",
    address: "강원특별자치도 춘천시 춘의로 111",
    district: "춘천시",
    officeCode: "K10",
    lat: 37.8813,
    lng: 127.73,
    source: "dummy",
  },
  {
    id: "dummy-chungbuk-office",
    name: "충청북도교육청",
    type: "office",
    address: "충청북도 청주시 흥덕구 공단로 87",
    district: "청주시",
    officeCode: "M10",
    lat: 36.6424,
    lng: 127.489,
    source: "dummy",
  },
  {
    id: "dummy-chungnam-office",
    name: "충청남도교육청",
    type: "office",
    address: "충청남도 홍성군 홍북읍 충남대로 21",
    district: "홍성군",
    officeCode: "N10",
    lat: 36.659,
    lng: 126.673,
    source: "dummy",
  },
  {
    id: "dummy-jeonbuk-office",
    name: "전북특별자치도교육청",
    type: "office",
    address: "전북특별자치도 전주시 완산구 홍산로 111",
    district: "전주시",
    officeCode: "P10",
    lat: 35.821,
    lng: 127.1089,
    source: "dummy",
  },
  {
    id: "dummy-jeonnam-office",
    name: "전라남도교육청",
    type: "office",
    address: "전라남도 무안군 삼향읍 남악로 38",
    district: "무안군",
    officeCode: "Q10",
    lat: 34.8161,
    lng: 126.4629,
    source: "dummy",
  },
  {
    id: "dummy-gyeongbuk-office",
    name: "경상북도교육청",
    type: "office",
    address: "경상북도 안동시 서동문로 121",
    district: "안동시",
    officeCode: "R10",
    lat: 36.5684,
    lng: 128.7294,
    source: "dummy",
  },
  {
    id: "dummy-gyeongnam-office",
    name: "경상남도교육청",
    type: "office",
    address: "경상남도 창원시 의창구 중앙대로 136",
    district: "창원시",
    officeCode: "S10",
    lat: 35.2272,
    lng: 128.6811,
    source: "dummy",
  },
  {
    id: "dummy-jeju-office",
    name: "제주특별자치도교육청",
    type: "office",
    address: "제주특별자치도 제주시 문연로 5",
    district: "제주시",
    officeCode: "T10",
    lat: 33.489,
    lng: 126.4983,
    source: "dummy",
  },
];

export function searchDummyInstitutions(
  query: string,
  officeCode: string = DEFAULT_OFFICE_CODE,
  district?: string,
): Institution[] {
  const normalized = query.trim().toLowerCase();

  return DUMMY_INSTITUTIONS.filter((item) => {
    const matchesOffice =
      officeCode === NATIONWIDE_OFFICE_CODE || item.officeCode === officeCode;
    const matchesDistrict = !district || district === "all" || item.district === district;
    if (!matchesOffice || !matchesDistrict) return false;
    if (!normalized) return true;

    const haystack = [
      item.name,
      item.address,
      item.district,
      ...(item.keywords ?? []),
    ]
      .join(" ")
      .toLowerCase();

    return haystack.includes(normalized);
  }).sort((a, b) => {
    if (a.type === b.type) return a.name.localeCompare(b.name, "ko");
    if (a.type === "office") return -1;
    if (b.type === "office") return 1;
    return a.name.localeCompare(b.name, "ko");
  });
}
